### ISSUE TITLE
Adding few Seahorse lang resources

### ISSUE THREAD

**Issue by hydrogenbond007** [hokage-candidates/awesome-solana#1]
Many folks were building tutorials for the Seahorse lang cookbook would be dope to add it here! 
https://seahorse-cookbook.vercel.app/programlibrary

**Comment by ngundotra** [comment]
Hey @hydrogenbond007 who maintains this? This seems like it might end up being a really good resource

**Comment by hydrogenbond007** [comment]
Some folks from superteam dao are working on this, the one I shared is just like the first draft more cool stuff to come! Myself working on some cool seahorse examples to add!

**Comment by swaroopmaddu** [comment]
@hydrogenbond007 instead of vercel link it's good to use https://www.seahorsecookbook.com/

**Comment by hydrogenbond007** [comment]
dope! thanks for sharing the new link, just shared the vercel link as soon as I got it lol

**Comment by ngundotra** [comment]
Added! Thanks for sharing links!
